/*******************************************************************
* Copyright (C) 2010-2020 Xilinx, Inc. All rights reserved.
* SPDX-License-Identifier: MIT
*******************************************************************/


#include "vprocss.h"
#include "vprocss_hw_config.h"
/*
* Subsystem Instance: <v_proc_ss_0>
*   - List of sub-cores included in the subsystem
*/

#define XPAR_HDMI_PATH_V_PROC_SS_0_CSC_PRESENT	 0
#define XPAR_HDMI_PATH_V_PROC_SS_0_HCR_PRESENT	 0
#define XPAR_HDMI_PATH_V_PROC_SS_0_HSC_PRESENT	 1
#define XPAR_HDMI_PATH_V_PROC_SS_0_RESET_SEL_AXIS_PRESENT	 1
#define XPAR_HDMI_PATH_V_PROC_SS_0_VCR_I_PRESENT	 0
#define XPAR_HDMI_PATH_V_PROC_SS_0_VCR_O_PRESENT	 0
#define XPAR_HDMI_PATH_V_PROC_SS_0_AXIS_SWITCH_0_PRESENT	 0
#define XPAR_HDMI_PATH_V_PROC_SS_0_V_VSCALER_PRESENT	 1


/*
* List of sub-cores excluded from the subsystem <v_proc_ss_0>
*   - Excluded sub-core device id is set to 255
*   - Excluded sub-core base address is set to 0
*/




XVprocSs_Config XVprocSs_ConfigTable[] =
{
	{
		XPAR_HDMI_PATH_V_PROC_SS_0_DEVICE_ID,
		XPAR_HDMI_PATH_V_PROC_SS_0_BASEADDR,
		XPAR_HDMI_PATH_V_PROC_SS_0_HIGHADDR,
		XPAR_HDMI_PATH_V_PROC_SS_0_TOPOLOGY,
		XPAR_HDMI_PATH_V_PROC_SS_0_SAMPLES_PER_CLK,
		XPAR_HDMI_PATH_V_PROC_SS_0_MAX_DATA_WIDTH,
		XPAR_HDMI_PATH_V_PROC_SS_0_NUM_VIDEO_COMPONENTS,
		XPAR_HDMI_PATH_V_PROC_SS_0_MAX_COLS,
		XPAR_HDMI_PATH_V_PROC_SS_0_MAX_ROWS,

		{
			XPAR_HDMI_PATH_V_PROC_SS_0_AXIS_SWITCH_0_PRESENT,
			XPAR_HDMI_PATH_V_PROC_SS_0_AXIS_SWITCH_0_DEVICE_ID,
			XPAR_HDMI_PATH_V_PROC_SS_0_AXIS_SWITCH_0_BASEADDR
		},
                {
			XPAR_HDMI_PATH_V_PROC_SS_0_RESET_SEL_AXIS_PRESENT,
			XPAR_HDMI_PATH_V_PROC_SS_0_RESET_SEL_AXIS_DEVICE_ID,
			XPAR_HDMI_PATH_V_PROC_SS_0_RESET_SEL_AXIS_BASEADDR
		},
   		{
			XPAR_HDMI_PATH_V_PROC_SS_0_HCR_PRESENT,
			XPAR_HDMI_PATH_V_PROC_SS_0_HCR_DEVICE_ID,
			XPAR_HDMI_PATH_V_PROC_SS_0_HCR_S_AXI_CTRL_BASEADDR
		},
                {
			XPAR_HDMI_PATH_V_PROC_SS_0_VCR_I_PRESENT,
			XPAR_HDMI_PATH_V_PROC_SS_0_VCR_I_DEVICE_ID,
			XPAR_HDMI_PATH_V_PROC_SS_0_VCR_I_S_AXI_CTRL_BASEADDR
		},
		{
			XPAR_HDMI_PATH_V_PROC_SS_0_VCR_O_PRESENT,
			XPAR_HDMI_PATH_V_PROC_SS_0_VCR_O_DEVICE_ID,
			XPAR_HDMI_PATH_V_PROC_SS_0_VCR_O_S_AXI_CTRL_BASEADDR
		},
		{
			XPAR_HDMI_PATH_V_PROC_SS_0_V_VSCALER_PRESENT,
			XPAR_HDMI_PATH_V_PROC_SS_0_V_VSCALER_DEVICE_ID,
			XPAR_HDMI_PATH_V_PROC_SS_0_V_VSCALER_S_AXI_CTRL_BASEADDR
		},
		{
			XPAR_HDMI_PATH_V_PROC_SS_0_HSC_PRESENT,
			XPAR_HDMI_PATH_V_PROC_SS_0_HSC_DEVICE_ID,
			XPAR_HDMI_PATH_V_PROC_SS_0_HSC_S_AXI_CTRL_BASEADDR
		},
		{
			XPAR_HDMI_PATH_V_PROC_SS_0_CSC_PRESENT,
			XPAR_HDMI_PATH_V_PROC_SS_0_CSC_DEVICE_ID,
			XPAR_HDMI_PATH_V_PROC_SS_0_CSC_S_AXI_CTRL_BASEADDR
		},
		
	}
};
